import type { Mechanism } from "./types";

/** Benzene & aromatic compounds — EAS (Persian lecture notes: «بنزن و ترکیبات آروماتیک» + McMurry ch. 14–15). */
export const AROMATIC_MECHANISMS: Mechanism[] = [
  {
    id: "eas-general",
    family: "eas",
    topic: "aromatics",
    source: { en: "McMurry ch. 15 · lecture notes (benzene)", fa: "مک‌موری فصل ۱۵ · جزوهٔ فصل بنزن" },
    tags: {
      en: ["sigma complex", "template", "arene"],
      fa: ["کمپلکس سیگما", "الگو", "آرن"],
    },
    en: {
      title: "Electrophilic aromatic substitution — the master template",
      summary:
        "All five classic EAS reactions share one three-step logic: (1) an electrophile is GENERATED by a reagent, (2) the ring's π electrons attack it forming a sigma complex (arenium ion), (3) a base removes H⁺ and aromaticity is restored. Substitution, not addition — because addition would destroy the aromatic sextet.",
      general: "Ar–H + E⁺ -> [Ar–H(E)]⁺ -> Ar–E + H⁺",
      steps: [
        { label: "Step 1 — electrophile generation", detail: "A catalyst/acid turns the reagent into a real electrophile: NO₂⁺ from HNO₃/H₂SO₄, Br⁺-like from Br₂/FeBr₃, CH₃⁺ from CH₃Cl/AlCl₃, SO₃ from fuming H₂SO₄." },
        { label: "Step 2 — sigma complex (rate-determining)", detail: "The ring's π electrons bond to E⁺, sacrificing aromaticity. The positive charge is delocalized over ortho/para positions in the arenium ion — this slow step decides the rate." },
        { label: "Step 3 — deprotonation", detail: "A base (HSO₄⁻, FeBr₄⁻, AlCl₄⁻) removes the proton from the substituted carbon; the π system closes up and aromaticity — the ~150 kJ/mol prize — is restored. Fast step." },
      ],
      keyPoints: [
        "The ring is a NUCLEOPHILE — it needs a real electrophile, that's all.",
        "Why substitution not addition? Regaining aromaticity is the thermodynamic payoff.",
        "Substituents direct: activators (–OH, –NH₂, alkyl) → ortho/para; deactivators (–NO₂, –COOH, halogens) → meta (halogens are deactivating but still o/p-directing).",
      ],
      conditions: "Each variant has its own electrophile/catalyst pair (see nitration, bromination, sulfonation, Friedel–Crafts).",
    },
    fa: {
      title: "جانشینی الکترون‌خواهی آروماتیک — الگوی مادر",
      summary:
        "هر پنج واکنش کلاسیک EAS یک منطق سه‌مرحله‌ای دارند: (۱) الکترون‌خواه توسط واکنش‌دهنده ساخته می‌شود، (۲) الکترون‌های π حلقه به آن حمله می‌کنند و کمپلکس سیگما (یون آرنیوم) می‌سازند، (۳) یک باز پروتون را برمی‌دارد و آروماتیک‌بودن بازمی‌گردد. جانشینی، نه افزایش — چون افزایش شش‌تایی آروماتیک را نابود می‌کند.",
      general: "Ar–H + E⁺ -> [Ar–H(E)]⁺ -> Ar–E + H⁺",
      steps: [
        { label: "مرحلهٔ ۱ — ساخت الکترون‌خواه", detail: "کاتالیزور/اسید واکنش‌دهنده را به الکترون‌خواه واقعی تبدیل می‌کند: NO₂⁺ از HNO₃/H₂SO₄، برم‌مانند از Br₂/FeBr₃، CH₃⁺ از CH₃Cl/AlCl₃ و SO₃ از H₂SO₄ دودکننده." },
        { label: "مرحلهٔ ۲ — کمپلکس سیگما (تعیین سرعت)", detail: "الکترون‌های π حلقه به E⁺ پیوند می‌خورند و آروماتیک‌بودن فدای آن می‌شود. بار مثبت در یون آرنیوم روی موقعیت‌های اورت/پارا غیرمتمرکز است — همین مرحلهٔ کند سرعت را تعیین می‌کند." },
        { label: "مرحلهٔ ۳ — جدا شدن پروتون", detail: "یک باز (HSO₄⁻، FeBr₄⁻، AlCl₄⁻) پروتون کربن جای‌گرفته را برمی‌دارد؛ سیستم π بسته می‌شود و جایزهٔ ~۱۵۰ کیلوژول بر مول — آروماتیک‌بودن — برمی‌گردد. مرحلهٔ سریع." },
      ],
      keyPoints: [
        "حلقه یک هسته‌خواه است — فقط به یک الکترون‌خواه واقعی نیاز دارد.",
        "چرا جانشینی و نه افزایش؟ بازیابی آروماتیک‌بودن، پاداش ترمودینامیکی است.",
        "جهت‌دهی جایگزین‌ها: فعال‌کننده‌ها (–OH، –NH₂، آلکیل) ← اورت/پارا؛ غیرفعال‌کننده‌ها (–NO₂، –COOH) ← متا (هالوژن‌ها غیرفعال‌کننده اما اورت/پارا-جهت‌اند).",
      ],
      conditions: "هر گونه جفت الکترون‌خواه/کاتالیزور خودش را دارد (نیتراسیون، بروماسیون، سولفوناسیون، فریدل–کرافتس).",
    },
    examples: [
      { name: { en: "Template", fa: "الگو" }, equation: "C6H6 + E+ -> C6H5E + H+" },
    ],
    related: ["ch15-nitration", "ch15-bromination", "ch15-friedel-crafts"],
  },
  {
    id: "eas-nitration",
    family: "eas",
    topic: "aromatics",
    source: { en: "McMurry ch. 15 · lecture notes", fa: "مک‌موری فصل ۱۵ · جزوهٔ فصل بنزن" },
    tags: {
      en: ["nitronium", "mixed acid", "50 °C"],
      fa: ["نیترونیوم", "اسید مخلوط", "۵۰ درجه"],
    },
    en: {
      title: "Nitration of benzene",
      summary:
        "Sulfuric acid protonates nitric acid; water leaves and the nitronium ion (NO₂⁺) forms. The ring attacks it, the sigma complex forms, and HSO₄⁻ removes the proton. Temperature control decides mono- vs dinitration.",
      general: "C6H6 + HNO3 -> H2SO4 -> C6H5NO2 + H2O",
      steps: [
        { label: "Step 1 — make NO₂⁺", detail: "HNO₃ + H₂SO₄ → H₂NO₃⁺ → NO₂⁺ + H₂O. The nitronium ion is linear and strongly electrophilic." },
        { label: "Step 2 — sigma complex", detail: "π electrons bond to N; the arenium ion carries the charge over ortho/para carbons." },
        { label: "Step 3 — deprotonation", detail: "HSO₄⁻ removes H⁺, restoring aromaticity and regenerating H₂SO₄ (catalytic)." },
      ],
      keyPoints: [
        "Keep ~50 °C: colder = nothing, hotter = dinitration (–NO₂ deactivates the ring but slow second addition still creeps in).",
        "Nitrobenzene: pale yellow, almond smell, the standard deactivated-ring substrate for meta chemistry.",
        "Reduction of –NO₂ (Sn/HCl or Fe/HCl) → aniline → diazonium chemistry: the whole door to aryl amines.",
      ],
      conditions: "Conc. HNO₃ + conc. H₂SO₄ ('mixed acid'), 40–60 °C, dropwise addition with cooling.",
    },
    fa: {
      title: "نیتراسیون بنزن",
      summary:
        "اسید سولفوریک، اسید نیتریک را پروتونه می‌کند؛ آب خارج می‌شود و یون نیترونیوم (NO₂⁺) ساخته می‌شود. حلقه به آن حمله می‌کند، کمپلکس سیگما شکل می‌گیرد و HSO₄⁻ پروتون را برمی‌دارد. کنترل دما تعیین می‌کند یک یا دو گروه نیتراژه.",
      general: "C6H6 + HNO3 -> H2SO4 -> C6H5NO2 + H2O",
      steps: [
        { label: "مرحلهٔ ۱ — ساخت NO₂⁺", detail: "HNO₃ + H₂SO₄ ← H₂NO₃⁺ ← NO₂⁺ + H₂O. یون نیترونیوم خطی و به‌شدت الکترون‌خواه است." },
        { label: "مرحلهٔ ۲ — کمپلکس سیگما", detail: "الکترون‌های π به نیتروژن پیوند می‌خورند؛ یون آرنیوم بار را روی کربن‌های اورت/پارا حمل می‌کند." },
        { label: "مرحلهٔ ۳ — جدا کردن پروتون", detail: "HSO₄⁻ پروتون را برمی‌دارد؛ آروماتیک‌بودن بازمی‌گردد و H₂SO₄ (کاتالیزوری) بازیابی می‌شود." },
      ],
      keyPoints: [
        "حدود ۵۰ درجه نگه دارید: سردتر = هیچ، گرم‌تر = دینیتراسیون (–NO₂ حلقه را غیرفعال می‌کند اما افزودن دوم آرام پیش می‌آید).",
        "نیتروبنزن: زرد کم‌رنگ با بوی بادام؛ زیرلایهٔ استاندارد حلقهٔ غیرفعال برای شیمی متا.",
        "کاهش –NO₂ (Sn/HCl یا Fe/HCl) ← آنیلین ← شیمی دی‌آزونیوم: درِ کامل مشتقات آمینی آروماتیک.",
      ],
      conditions: "HNO₃ غلیظ + H₂SO₄ غلیظ («اسید مخلوط»)، ۴۰–۶۰ درجه، افزودن قطره‌ای با سردکردن.",
    },
    examples: [
      { name: { en: "Benzene → nitrobenzene", fa: "بنزن ← نیتروبنزن" }, equation: "C6H6 + HNO3 -> H2SO4 -> C6H5NO2 + H2O" },
    ],
    related: ["ch15-nitration"],
  },
  {
    id: "eas-bromination",
    family: "eas",
    topic: "aromatics",
    source: { en: "McMurry ch. 15 · lecture notes", fa: "مک‌موری فصل ۱۵ · جزوهٔ فصل بنزن" },
    tags: {
      en: ["FeBr3", "Lewis acid", "contrast alkenes"],
      fa: ["FeBr3", "اسید لوئیس", "مقایسه با آلکن"],
    },
    en: {
      title: "Bromination of benzene (Lewis-acid catalyzed)",
      summary:
        "Benzene ignores Br₂ by itself — aromaticity makes it a weak nucleophile. FeBr₃ polarizes Br₂ into Br⁺-like electrophile; the ring attacks, FeBr₄⁻ deprotonates, HBr escapes. The direct contrast with the alkene bromine test.",
      general: "C6H6 + Br2 -> FeBr3 -> C6H5Br + HBr",
      steps: [
        { label: "Step 1 — polarization", detail: "Br₂ coordinates to FeBr₃ → Br–Br⁺–FeBr₃⁻ complex; the terminal Br is now electrophilic enough for the ring." },
        { label: "Step 2 — sigma complex", detail: "π electrons attack the Br⁺; arenium ion + FeBr₄⁻ form." },
        { label: "Step 3 — deprotonation", detail: "FeBr₄⁻ removes H⁺ → HBr + FeBr₃ (catalyst recovered)." },
      ],
      keyPoints: [
        "Alkene + Br₂: instant, no catalyst. Benzene + Br₂: nothing without FeBr₃. Aromaticity's price in one comparison.",
        "Cl₂/AlCl₃ works the same for chlorination; I₂ needs an oxidant (HNO₃) because the reaction is reversible.",
        "HBr escaping the mixture pulls the equilibrium forward (Le Chatelier assist).",
      ],
      conditions: "Br₂ + catalytic FeBr₃ (or AlBr₃), anhydrous, room temperature.",
    },
    fa: {
      title: "بروماسیون بنزن (کاتالیز اسید لوئیس)",
      summary:
        "بنزن بدون کمک، Br₂ را نادیده می‌گیرد — آروماتیک‌بودن آن را هسته‌خواهی ضعیف کرده. FeBr₃ برم را به الکترون‌خواهی شبیه Br⁺ قطبی می‌کند؛ حلقه حمله می‌کند، FeBr₄⁻ پروتون را می‌گیرد و HBr خارج می‌شود. مقایسهٔ مستقیم با آزمون برومِ آلکن‌ها.",
      general: "C6H6 + Br2 -> FeBr3 -> C6H5Br + HBr",
      steps: [
        { label: "مرحلهٔ ۱ — قطبش", detail: "Br₂ به FeBr₃ مختص می‌شود ← کمپلکس Br–Br⁺–FeBr₃⁻؛ بروم انتهایی حالا برای حلقه به‌اندازهٔ کافی الکترون‌خواه است." },
        { label: "مرحلهٔ ۲ — کمپلکس سیگما", detail: "الکترون‌های π به Br⁺ حمله می‌کنند ← یون آرنیوم + FeBr₄⁻." },
        { label: "مرحلهٔ ۳ — جدا شدن پروتون", detail: "FeBr₄⁻ پروتون را برمی‌دارد ← HBr + FeBr₃ (کاتالیزور بازیابی)." },
      ],
      keyPoints: [
        "آلکن + Br₂: فوری و بدون کاتالیزور. بنزن + Br₂: بدون FeBr₃ هیچ. قیمت آروماتیک‌بودن در یک مقایسه.",
        "Cl₂/AlCl₃ برای کلراسیون همین‌طور کار می‌کند؛ I₂ به اکساینده (HNO₃) نیاز دارد چون واکنش برگشت‌پذیر است.",
        "خروج HBr از مخلوط، تعادل را به جلو می‌برد (کمک لو شاتلیه).",
      ],
      conditions: "Br₂ + FeBr₃ کاتالیزوری (یا AlBr₃)، بدون آب، دمای اتاق.",
    },
    examples: [
      { name: { en: "Benzene → bromobenzene", fa: "بنزن ← بروموبنزن" }, equation: "C6H6 + Br2 -> FeBr3 -> C6H5Br + HBr" },
    ],
    related: ["ch15-bromination"],
  },
  {
    id: "eas-friedel-crafts",
    family: "eas",
    topic: "aromatics",
    source: { en: "McMurry ch. 15 · lecture notes", fa: "مک‌موری فصل ۱۵ · جزوهٔ فصل بنزن" },
    tags: {
      en: ["AlCl3", "C–C bond", "polyalkylation"],
      fa: ["AlCl3", "پیوند C–C", "چندآلکیل‌شدگی"],
    },
    en: {
      title: "Friedel–Crafts alkylation & acylation",
      summary:
        "AlCl₃ abstracts a halide to expose a carbocation (alkylation) or acylium ion (acylation); the ring attacks and builds a C–C bond directly on the aromatic ring. Alkylation over-reacts; acylation stops after one.",
      general: "C6H6 + RCl -> AlCl3 -> C6H5R + HCl   |   + RCOCl -> C6H5COR",
      steps: [
        { label: "Step 1 — electrophile generation", detail: "R–Cl + AlCl₃ → R⁺(tight pair) + AlCl₄⁻. With acyl chlorides the resonance-stabilized acylium ion R–C≡O⁺ forms." },
        { label: "Step 2 — sigma complex", detail: "Ring attacks the cation → arenium ion." },
        { label: "Step 3 — deprotonation", detail: "AlCl₄⁻ removes H⁺ → product + HCl + AlCl₃." },
      ],
      keyPoints: [
        "Alkylation: the alkyl product is MORE activated than benzene → polyalkylation; use excess benzene.",
        "Acylation: the acyl group deactivates the ring → stops at mono; then reduction (Clemmensen) gives the alkyl product cleanly.",
        "Limits: carbocation rearrangements (CH₃CH₂CH₂⁺ → isopropyl); fails on strongly deactivated rings and on –NH₂/–NHR substrates (they complex AlCl₃).",
      ],
      conditions: "Anhydrous AlCl₃ (dry everything!), RCl/RCOCl, inert solvent or excess arene.",
    },
    fa: {
      title: "آلکیل‌دار کردن و آسیل‌دار کردن فریدل–کرافتس",
      summary:
        "AlCl₃ هالید را می‌رباید و کاتیون (در آلکیل‌دار کردن) یا یون آسیلیوم (در آسیل‌دار کردن) را آشکار می‌کند؛ حلقه حمله می‌کند و پیوند C–C مستقیم روی حلقهٔ آروماتیک ساخته می‌شود. آلکیل‌دار کردن بیش‌واکنشی می‌کند؛ آسیل‌دار کردن بعد از یکی می‌ایستد.",
      general: "C6H6 + RCl -> AlCl3 -> C6H5R + HCl   |   + RCOCl -> C6H5COR",
      steps: [
        { label: "مرحلهٔ ۱ — ساخت الکترون‌خواه", detail: "R–Cl + AlCl₃ ← R⁺(جفت تنگ) + AlCl₄⁻. با آسیل کلریدها، یون آسیلیوم پایدارشده با رزونانس R–C≡O⁺ شکل می‌گیرد." },
        { label: "مرحلهٔ ۲ — کمپلکس سیگما", detail: "حلقه به کاتیون حمله می‌کند ← یون آرنیوم." },
        { label: "مرحلهٔ ۳ — جدا کردن پروتون", detail: "AlCl₄⁻ پروتون را برمی‌دارد ← محصول + HCl + AlCl₃." },
      ],
      keyPoints: [
        "آلکیل‌دار کردن: محصولِ آلکیلی، فعال‌تر از بنزن است ← چندآلکیل‌شدگی؛ بنزن اضافه مصرف کنید.",
        "آسیل‌دار کردن: گروه آسیلی حلقه را غیرفعال می‌کند ← در یکی می‌ایستد؛ سپس کاهش (کلمانسن) آلکیلِ تمیز می‌دهد.",
        "محدودیت‌ها: بازآرایی کاتیونی (CH₃CH₂CH₂⁺ ← ایزوپروپیل)؛ روی حلقه‌های به‌شدت غیرفعال و زیرلایه‌های –NH₂/–NHR (که با AlCl₃ کمپلکس می‌دهند) شکست می‌خورد.",
      ],
      conditions: "AlCl₃ بدون آب (همه‌چیز باید خشک باشد!)، RCl/RCOCl، حلال بی‌اثر یا آرن اضافه.",
    },
    examples: [
      { name: { en: "Benzene + CH₃Cl → toluene", fa: "بنزن + CH₃Cl ← تولوئن" }, equation: "C6H6 + CH3Cl -> AlCl3 -> C6H5CH3 + HCl" },
      { name: { en: "Acylation", fa: "آسیل‌دار کردن" }, equation: "C6H6 + CH3COCl -> AlCl3 -> C6H5COCH3 + HCl" },
    ],
    related: ["ch15-friedel-crafts"],
  },
  {
    id: "aromatic-hydrogenation-resistance",
    family: "redox",
    topic: "aromatics",
    source: { en: "McMurry ch. 14–15 · lecture notes", fa: "مک‌موری فصول ۱۴–۱۵ · جزوه‌ها" },
    tags: {
      en: ["aromaticity", "reluctance", "cyclohexane"],
      fa: ["آروماتیک‌بودن", "مقاومت", "سیکلوهگزان"],
    },
    en: {
      title: "Aromatic resistance — forcing hydrogenation",
      summary:
        "The delocalized π sextet (~150 kJ/mol stabilization) refuses normal alkene hydrogenation. Only harsh catalytic conditions (Ni, ~200 °C, high H₂ pressure) push three equivalents of H₂ into benzene → cyclohexane.",
      general: "C6H6 + 3 H2 -> Ni, 200C -> C6H12",
      steps: [
        { label: "Why so reluctant?", detail: "Each addition step would locally destroy aromatic stabilization; the first H₂ is uphill until enough π bonds are broken that the rest follows." },
        { label: "The forcing conditions", detail: "High T/P on Ni/Pt overcomes the barrier; once the first ring hydrogenation completes, the rest is fast." },
      ],
      keyPoints: [
        "The very reluctance IS the evidence for aromaticity.",
        "Industrially vital: cyclohexane → adipic acid → nylon.",
        "Electron-poor rings (pyridine) are even harder; electron-rich (furan, thiophene) hydrogenate more easily.",
      ],
      conditions: "Ni or Pt catalyst, ~200 °C, elevated H₂ pressure (3 equiv).",
    },
    fa: {
      title: "مقاومت آروماتیک — هیدروژن‌دار کردن اجباری",
      summary:
        "شش‌تایی π غیرمتمرکز (~۱۵۰ کیلوژول بر مول پایداری) حاضر به هیدروژن‌دار کردن معمولی آلکنی نیست. فقط شرایط کاتالیزی سخت (Ni، حدود ۲۰۰ درجه، فشار بالای H₂) سه هم‌ارز H₂ را به بنزن وارد می‌کند ← سیکلوهگزان.",
      general: "C6H6 + 3 H2 -> Ni, 200C -> C6H12",
      steps: [
        { label: "چرا این‌قدر مقاوم؟", detail: "هر گام افزودن، پایداری آروماتیک را موضعی از بین می‌برد؛ اولین H₂ سربالایی است تا وقتی πهای کافی شکسته شود و بقیه دنبالش بیاید." },
        { label: "شرایط اجباری", detail: "دما/فشار بالا روی Ni/Pt سد انرژی را جارو می‌کند؛ وقتی اولین هیدروژن‌دار شدن کامل شد، بقیه سریع است." },
      ],
      keyPoints: [
        "خودِ مقاومت، شاهدِ آروماتیک‌بودن است.",
        "صنعتی حیاتی: سیکلوهگزان ← اسید آدیپیک ← نایلون.",
        "حلقه‌های کم‌الکترون (پیریدین) سخت‌تر؛ پرالکترون (فوران، تیوفن) آسان‌تر هیدروژن‌دار می‌شوند.",
      ],
      conditions: "کاتالیزور Ni یا Pt، حدود ۲۰۰ درجه، فشار بالای H₂ (۳ هم‌ارز).",
    },
    examples: [
      { name: { en: "Benzene → cyclohexane", fa: "بنزن ← سیکلوهگزان" }, equation: "C6H6 + 3 H2 -> Ni -> C6H12" },
    ],
    related: ["ch14-aromatic-hydrogenation"],
  },
];
